### ISSUE TITLE
Can not Add Credentials

### ISSUE THREAD

**Issue by gvargas9** [n8n-ninja/n8n-nodes-elevenlabs#1]
Installed 
n8n-nodes-elevenlabs 1 node:  ElevenLabs. v0.0.3

No option to add API Key

<img width="521" alt="n8n - ▶️ GTP_Assistant_Gen 2024-05-17 09-57-33" src="https://github.com/n8n-ninja/n8n-nodes-elevenlabs/assets/22826821/27f03185-ffa9-485a-b526-ef8a8be52a05">

**Comment by altomarketing** [comment]
The api key you should add inside your CREDENTIALS, in left MENU . Before creating the flow
![image](https://github.com/n8n-ninja/n8n-nodes-elevenlabs/assets/474889/7263015c-3ca7-4996-8c36-dddf99bad08d)

**Comment by gvargas9** [comment]
Thanks!

**Comment by KhDu** [comment]
I have the exact same problem and can't see it under credentials either
