### ISSUE TITLE
Do you plan to add request stiching support?

### ISSUE THREAD

**Issue by AlexfromAvanoo** [n8n-ninja/n8n-nodes-elevenlabs#2]
Hi,

Thank you for creating this node.
Do you plan to support request stiching?
It provides way better results for anything longer than a couples sentences.

Thanks!

https://elevenlabs.io/docs/api-reference/how-to-use-request-stitching

**Comment by n8n-ninja** [comment]
Hi @AlexfromSonar, 

That is one cool suggestion.
I will dig it next week. 

🥷

**Comment by n8n-ninja** [comment]
@AlexfromSonar

I deployed version 0.04 that supports request stitching. By default, it is not active; you can activate it in the additional fields.

I decided to implement only the first method. Let me know if it works well for your use case, and if needed, I will work on implementing the second possibility.

**Comment by AlexfromAvanoo** [comment]
Thanks @n8n-ninja ,

I've tried but I can't see the additional fields related to the request stitching, what am I missing?

Here are all additional fields I have.

![image](https://github.com/n8n-ninja/n8n-nodes-elevenlabs/assets/150655913/ef566385-1503-44bf-af65-4e05fcc60bc8)
